"""Canonical ``BrokerTarget`` enum.

This is the single source of truth for the broker_target string values that
the workflow uses to route Activities to the ``broker-<value>`` task queue.
The matching Java enum is generated by jsonschema2pojo as a nested type on
each DTO; jOOQ-side normalization happens in the Kotlin/Java codegen layer.

The generated ``models/*.py`` files re-import this enum via the
``regen.sh`` post-processing step (path A of the consolidation plan). A
pytest in ``tests/test_broker_target_single_source.py`` asserts no
generated file ever re-declares ``class BrokerTarget(StrEnum)`` locally.

Legacy bare values (``paper`` / ``live``) remain in the enum because old
audit records still carry them; the orchestrator's
``ExecActivitiesFactory.taskQueueFor`` rejects them with a non-retryable
``InvalidBrokerTargetError`` for active routing.
"""

from __future__ import annotations

from enum import StrEnum


class BrokerTarget(StrEnum):
    """Routes Activities to the ``broker-<value>`` Temporal task queue.

    Phase 2c.2 introduced the ``<provider>-<env>`` shape. The bare
    ``paper`` / ``live`` values are admitted ONLY for deserialization of
    pre-2c.2 audit records; using them for active routing produces a
    non-retryable ``InvalidBrokerTargetError`` because no worker polls
    ``broker-paper`` / ``broker-live``.
    """

    paper = "paper"
    live = "live"
    alpaca_paper = "alpaca-paper"
    alpaca_live = "alpaca-live"
    tradier_paper = "tradier-paper"
    tradier_live = "tradier-live"
    ibkr_paper = "ibkr-paper"
    ibkr_live = "ibkr-live"
    schwab_paper = "schwab-paper"
    schwab_live = "schwab-live"
