# generated by datamodel-codegen:
#   filename:  account-kill-switch-workflow-input.json

from __future__ import annotations

from datetime import date

from pydantic import AwareDatetime, BaseModel, ConfigDict, confloat, conint, constr


class AccountKillSwitchWorkflowInput(BaseModel):
    """
    Phase 6: input for AccountKillSwitchWorkflow. ONE workflow per tenant_id (NO strategy_id segment — the cap spans every strategy on the tenant's shared broker_target), bootstrapped on orchestrator startup with workflow_id t-<tenant>/account/killswitch. Mirrors KillSwitchWorkflowInput's carry-forward shape for continueAsNew. Fresh bootstrap inputs omit the carry-forward fields; replayed continueAsNew inputs populate them. v3 adds sod_equity so the start-of-day-equity pct cap's per-day equity snapshot survives a same-day continueAsNew. v4 adds consecutive_mtm_unavailable_ticks so the small-book mtm-unavailable fail-close debounce counter survives a same-day continueAsNew.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: conint(ge=1, le=4)
    """
    DTO contract version. v1 = bootstrap-only input; v2 adds optional carry-forward fields produced by continueAsNew; v3 adds the sod_equity carry-forward; v4 adds the consecutive_mtm_unavailable_ticks carry-forward. Workers reject newer-than-build inputs.
    """
    tenant_id: constr(min_length=1)
    tripped: bool | None = None
    """
    Carry-forward state from a prior run. Absent on fresh bootstrap. Default false.
    """
    reason: str | None = None
    """
    Carry-forward trip reason from a prior run. Absent on fresh bootstrap.
    """
    actor: str | None = None
    """
    Carry-forward trip actor from a prior run. Absent on fresh bootstrap.
    """
    tripped_at: AwareDatetime | None = None
    """
    Carry-forward trip timestamp from a prior run. Absent on fresh bootstrap.
    """
    cooling_down_until: AwareDatetime | None = None
    """
    Carry-forward reset cooldown deadline from a prior run. Absent on fresh bootstrap.
    """
    trading_day: date | None = None
    """
    Carry-forward trading day from a prior run. Absent on fresh bootstrap; next heartbeat refreshes via calendar.todayEt().
    """
    sod_equity: confloat(ge=0.0) | None = None
    """
    Carry-forward start-of-day account equity for trading_day, captured once per day for the account_daily_loss_pct cap. Absent on fresh bootstrap and re-captured on each day rollover; carried across continueAsNew so a same-day CAN does not re-read it. v3+.
    """
    consecutive_mtm_unavailable_ticks: conint(ge=0) | None = None
    """
    Carry-forward count of CONSECUTIVE unpriceable-book heartbeats accumulated toward the small-book mtm-unavailable fail-close debounce (MTM_UNAVAILABLE_TRIP_TICKS). Carried across continueAsNew so a same-day CAN mid-debounce does not reset the count. Absent on fresh bootstrap and when the count is 0. v4+.
    """
