# generated by datamodel-codegen:
#   filename:  account-kill-switch-workflow-input.json

from __future__ import annotations

from datetime import date
from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class AccountKillSwitchWorkflowInput(BaseModel):
    """
    Phase 6: input for AccountKillSwitchWorkflow. ONE workflow per tenant_id (NO strategy_id segment — the cap spans every strategy on the tenant's shared broker_target), bootstrapped on orchestrator startup with workflow_id t-<tenant>/account/killswitch. Mirrors KillSwitchWorkflowInput's carry-forward shape for continueAsNew. Fresh bootstrap inputs omit the carry-forward fields; replayed continueAsNew inputs populate them. v3 adds sod_equity so the start-of-day-equity pct cap's per-day equity snapshot survives a same-day continueAsNew. v4 adds consecutive_mtm_unavailable_ticks so the small-book mtm-unavailable fail-close debounce counter survives a same-day continueAsNew. v5 adds last_open_positions/last_open_mtm so the reset-banner open-exposure cache survives a same-day continueAsNew (else the exposure is blank for up to one heartbeat after a CAN).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Annotated[int, Field(ge=1, le=5)]
    """
    DTO contract version. v1 = bootstrap-only input; v2 adds optional carry-forward fields produced by continueAsNew; v3 adds the sod_equity carry-forward; v4 adds the consecutive_mtm_unavailable_ticks carry-forward; v5 adds the last_open_positions/last_open_mtm exposure-cache carry-forward. Workers reject newer-than-build inputs.
    """
    tenant_id: Annotated[str, Field(min_length=1)]
    tripped: bool | None = None
    """
    Carry-forward state from a prior run. Absent on fresh bootstrap. Default false.
    """
    reason: str | None = None
    """
    Carry-forward trip reason from a prior run. Absent on fresh bootstrap.
    """
    actor: str | None = None
    """
    Carry-forward trip actor from a prior run. Absent on fresh bootstrap.
    """
    tripped_at: AwareDatetime | None = None
    """
    Carry-forward trip timestamp from a prior run. Absent on fresh bootstrap.
    """
    cooling_down_until: AwareDatetime | None = None
    """
    Carry-forward reset cooldown deadline from a prior run. Absent on fresh bootstrap.
    """
    trading_day: date | None = None
    """
    Carry-forward trading day from a prior run. Absent on fresh bootstrap; next heartbeat refreshes via calendar.todayEt().
    """
    sod_equity: Annotated[float | None, Field(ge=0.0)] = None
    """
    Carry-forward start-of-day account equity for trading_day, captured once per day for the account_daily_loss_pct cap. Absent on fresh bootstrap and re-captured on each day rollover; carried across continueAsNew so a same-day CAN does not re-read it. v3+.
    """
    consecutive_mtm_unavailable_ticks: Annotated[int | None, Field(ge=0)] = None
    """
    Carry-forward count of CONSECUTIVE unpriceable-book heartbeats accumulated toward the small-book mtm-unavailable fail-close debounce (MTM_UNAVAILABLE_TRIP_TICKS). Carried across continueAsNew so a same-day CAN mid-debounce does not reset the count. Absent on fresh bootstrap and when the count is 0. v4+.
    """
    last_open_positions: Annotated[int | None, Field(ge=0)] = None
    """
    Carry-forward listed open-position count cached from the last heartbeat that valued the book (the reset-banner exposure). Carried across continueAsNew so the exposure is not blank for up to one heartbeat after a same-day CAN. Absent on fresh bootstrap and until the first valued heartbeat. v5+.
    """
    last_open_mtm: float | None = None
    """
    Carry-forward SIGNED unrealized P&L ((liveBid-entry)*qty*100) cached from the last heartbeat that priced the book FULLY (quoteFailures==0). SIGNED — a positive value is a gain, not a loss. Carried across continueAsNew so the reset banner is not blank for up to one heartbeat after a same-day CAN; carried ONLY when the last heartbeat priced the book (a partial/absent valuation leaves it absent). Absent on fresh bootstrap and until the first fully-priced heartbeat. v5+.
    """
    last_still_tripped_page_day: date | None = None
    """
    #669 carry: the trading day the once-per-day still-tripped page last fired (or was quiet-stamped on the trip day). Carried across continue-as-new so the roll day neither loses its page nor duplicates it; absent on a pre-#669 carry, where the first tripped tick quiet-stamps (one page skipped, once, ever).
    """
