# generated by datamodel-codegen:
#   filename:  account-snapshot-request.json

from __future__ import annotations


from pydantic import BaseModel, ConfigDict, conint


from ohmytradeagent_contract.types.broker_target import BrokerTarget


class AccountSnapshotRequest(BaseModel):
    """
    Issue #317 account-equity gate input. risk-svc dispatches this to exec-svc's account_snapshot Activity to read the brokerage account's net-liquidation equity for the notional_cap_pct_of_equity gate. Equity is account-level: it is identified solely by broker_target (one credential set / one account per <provider>-<env> exec deployment), so this request carries NO tenant_id/strategy_id — every (tenant, strategy) routing to a given broker_target shares one account and observes the same equity.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: conint(ge=1)
    """
    DTO contract version. See CopytradeSignalPayload.schema_version.
    """
    broker_target: BrokerTarget
    """
    Routes the account-snapshot Activity to the broker-<value> task queue, mirroring PreTradeCheckRequest.broker_target and OrderIntent.broker_target.
    """
    correlation_id: str | None = None
    """
    Optional cross-event correlation key (typically signal_id).
    """
