# generated by datamodel-codegen:
#   filename:  account-kill-switch-workflow-input.json

from __future__ import annotations

from datetime import date

from pydantic import AwareDatetime, BaseModel, ConfigDict, conint, constr


class AccountKillSwitchWorkflowInput(BaseModel):
    """
    Phase 6: input for AccountKillSwitchWorkflow. ONE workflow per tenant_id (NO strategy_id segment — the cap spans every strategy on the tenant's shared broker_target), bootstrapped on orchestrator startup with workflow_id t-<tenant>/account/killswitch. Mirrors KillSwitchWorkflowInput's carry-forward shape for continueAsNew. Fresh bootstrap inputs omit the carry-forward fields; replayed continueAsNew inputs populate them.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: conint(ge=1, le=2)
    """
    DTO contract version. v1 = bootstrap-only input; v2 adds optional carry-forward fields produced by continueAsNew. Workers reject newer-than-build inputs.
    """
    tenant_id: constr(min_length=1)
    tripped: bool | None = None
    """
    Carry-forward state from a prior run. Absent on fresh bootstrap. Default false.
    """
    reason: str | None = None
    """
    Carry-forward trip reason from a prior run. Absent on fresh bootstrap.
    """
    actor: str | None = None
    """
    Carry-forward trip actor from a prior run. Absent on fresh bootstrap.
    """
    tripped_at: AwareDatetime | None = None
    """
    Carry-forward trip timestamp from a prior run. Absent on fresh bootstrap.
    """
    cooling_down_until: AwareDatetime | None = None
    """
    Carry-forward reset cooldown deadline from a prior run. Absent on fresh bootstrap.
    """
    trading_day: date | None = None
    """
    Carry-forward trading day from a prior run. Absent on fresh bootstrap; next heartbeat refreshes via calendar.todayEt().
    """
