# generated by datamodel-codegen:
#   filename:  adoption-workflow-input.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, conint, constr


class AdoptionWorkflowInput(BaseModel):
    """
    Issue #285: input to the short-lived AdoptionWorkflow started by api-gateway POST /positions/adopt. Identifies the confirmed orphan (tenant, strategy, occ) to adopt and the operator who triggered it (provenance / audit). The workflow resolves broker_target from StrategyConfig to route its broker-truth ReconciliationExecActivity calls to the correct exec task queue (broker-<broker_target>); it is not an input field.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: conint(ge=1)
    tenant_id: constr(min_length=1)
    strategy_id: constr(min_length=1)
    occ: constr(min_length=1)
    """
    The orphaned OCC option symbol to adopt. Operator may supply the broker/audit compact form or the padded OccSymbol.of form; the workflow resolves the canonical padded form from the journal anchor.
    """
    operator_id: constr(min_length=1)
    """
    Operator who triggered the adoption (from X-Operator-Id). Recorded in the PositionAdopted audit provenance.
    """
