# generated by datamodel-codegen:
#   filename:  arm-decision.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, confloat


class ArmDecision(BaseModel):
    """
    Outcome of the arm gate for a watchlist trigger: whether to arm the trigger and at what size multiplier. Returned by the arm-decision step toward the trigger-strategy workflow.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    arm: bool
    """
    True to arm the trigger for subsequent fire evaluation; false to drop it.
    """
    size_multiplier: confloat(ge=0.0)
    """
    Position-size multiplier applied to the base allocation when the trigger eventually fires. 0 disables sizing without disarming.
    """
    reason: str | None = None
    """
    Optional human-readable reason for the arm decision (audit).
    """
