# generated by datamodel-codegen:
#   filename:  arm-chandelier-payload.json

from __future__ import annotations

from decimal import Decimal
from typing import Annotated

from pydantic import Field, BaseModel, ConfigDict, confloat, conint, constr


class ArmChandelierPayload(BaseModel):
    """
    Phase 4: signal payload to PositionWorkflow.arm_chandelier. Dispatched by CopytradeSignalWorkflow's STC branch when trail_on_partial is true. Idempotent — a second arm on an already-armed position is a silent no-op.
    """

    model_config = ConfigDict(
        extra="forbid",
        json_encoders={Decimal: float},
    )
    schema_version: conint(ge=1)
    """
    DTO contract version. See CopytradeSignalPayload.schema_version.
    """
    tenant_id: constr(min_length=1)
    strategy_id: constr(min_length=1)
    position_workflow_id: constr(min_length=1)
    """
    Target PositionWorkflow workflow_id.
    """
    source_signal_id: constr(min_length=1)
    """
    signal_id of the STC line that triggered the arm. Recorded for audit forensics.
    """
    peak_premium: Annotated[Decimal, Field(gt=0)]
    """
    Initial peak premium to anchor the trail at. Typically the STC ref_premium at arm time.
    """
    giveback_pct: confloat(le=0.5, gt=0.0)
    """
    Trailing-stop giveback fraction. fire_threshold = peak * (1 - giveback_pct).
    """
