# generated by datamodel-codegen:
#   filename:  arm-context.json

from __future__ import annotations

from datetime import date

from pydantic import BaseModel, ConfigDict


class ArmContext(BaseModel):
    """
    Minimal context supplied to the arm/fire gates for a watchlist trigger. Intentionally small and additively versionable: new fields are appended as optional. Reference: docs/plans/PLAN-watchlist-trigger.html.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    et_date: date
    """
    ET calendar date the gate is evaluating against (YYYY-MM-DD). Named et_date (not date) to avoid shadowing the date type in generated models.
    """
    cash: float | None = None
    """
    Optional broker account live CASH balance (dollars) available for sizing. Absent when the gate runs without an account snapshot.
    """
