# generated by datamodel-codegen:
#   filename:  audit-event.json

from __future__ import annotations

from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, conint, constr


class AuditEvent(BaseModel):
    """
    Append-only audit-log event scoped by (tenant_id, strategy_id). Every state-changing Activity in the system emits one.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: conint(ge=1)
    """
    DTO contract version. See CopytradeSignalPayload.schema_version.
    """
    tenant_id: constr(min_length=1)
    strategy_id: constr(min_length=1)
    event_id: constr(min_length=1)
    """
    UUID v4 for this event row.
    """
    occurred_at: AwareDatetime
    """
    RFC3339 UTC timestamp set by the originator of the event (broker for fills, sidecar for posted, workflow for decided).
    """
    kind: constr(min_length=1)
    """
    Event kind tag (e.g., SignalReceived, SignalRejected, EntryFilled, EntryExpired, ExitRequested, KillSwitchTripped, KillSwitchResetApproved, ReconciliationCompleted, JournalOrphan, BrokerOrphan, OrphanSTC, SymbolDriftDetected).
    """
    subject: dict[str, Any]
    """
    Free-form structured payload for the event. Schema-by-kind to be formalized as the system grows; v0 uses ad-hoc shape.
    """
    actor: str | None = None
    """
    Who or what produced this event (e.g., 'workflow:CopytradeSignalWorkflow', 'activity:exec.place_order', 'operator:ridopark').
    """
    workflow_id: str | None = None
    """
    Originating workflow ID, if applicable. Allows correlation across the audit log without joining Temporal history.
    """
    correlation_id: str | None = None
    """
    Optional cross-event correlation key (e.g., a signal_id linking SignalReceived → EntryFilled → ExitRequested).
    """
