# generated by datamodel-codegen:
#   filename:  broker-position.json

from __future__ import annotations

from decimal import Decimal
from typing import Annotated

from enum import StrEnum

from pydantic import Field, BaseModel, ConfigDict, conint, constr


class Side(StrEnum):
    """
    Phase 3 v0 supports LONG only; SHORT/inverse positions are not produced by copytrade.
    """

    long = "LONG"


class BrokerPosition(BaseModel):
    """
    A broker-held position returned by ReconciliationExecActivity.brokerListOpenPositions. Used by Phase 3 reconciliation to detect filled positions with no corresponding running PositionWorkflow (issue #165).
    """

    model_config = ConfigDict(
        extra="forbid",
        json_encoders={Decimal: float},
    )
    schema_version: conint(ge=1)
    option_symbol: constr(min_length=1)
    """
    OCC-formatted symbol, broker-native form (Alpaca: no padding).
    """
    qty: conint(ge=1)
    """
    Long contract count. Negative qty is out of scope for v0 — copytrade only opens long positions.
    """
    side: Side
    """
    Phase 3 v0 supports LONG only; SHORT/inverse positions are not produced by copytrade.
    """
    avg_entry_price: Annotated[Decimal, Field(gt=0)] | None = None
    """
    Optional avg entry price from broker. May be omitted if broker doesn't carry it.
    """
