# generated by datamodel-codegen:
#   filename:  broker-open-order.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, conint, constr


class Side(StrEnum):
    buy = "BUY"
    sell = "SELL"


class BrokerOpenOrder(BaseModel):
    """
    One open order as reported by the broker (Tradier sandbox in v0). Returned by exec.broker_list_open_orders Activity to ReconciliationWorkflow.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: conint(ge=1)
    broker_order_id: constr(min_length=1)
    client_order_id: constr(min_length=1)
    """
    Required even from broker — our place_order always sets it to intent_key. Mismatch here means the broker book contains an order we did not place.
    """
    option_symbol: constr(min_length=1)
    side: Side
    qty: conint(ge=1)
    state: str
    """
    Broker-native state string (e.g., 'open', 'partially_filled'). Reconciliation does not parse this; it is audit-only.
    """
