# generated by datamodel-codegen:
#   filename:  broker-credential-audit-request.json

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, ConfigDict, conint, constr


class ChangeType(StrEnum):
    """
    Whether this credential write created the first credential for the tenant/provider row (CREATE) or rotated an existing one (ROTATE).
    """

    create = "CREATE"
    rotate = "ROTATE"


class Outcome(StrEnum):
    """
    Controlled disposition of the write. A closed enum (no free-text reason) so the audit subject can never carry leaked key material. On any REJECTED_* outcome the optional broker_account_id/credential_version/kek_version are typically omitted.
    """

    saved = "SAVED"
    rejected_validation = "REJECTED_VALIDATION"
    rejected_account_mismatch = "REJECTED_ACCOUNT_MISMATCH"
    rejected_kek_unavailable = "REJECTED_KEK_UNAVAILABLE"
    rejected_persist_error = "REJECTED_PERSIST_ERROR"


class BrokerCredentialAuditRequest(BaseModel):
    """
    P6-d (multi-tenant-broker-credentials): metadata-only hash-chain audit input for a tenant broker credential write or rotation. Carries ZERO key material — the api-key/secret never appears here (P6-c's BrokerCredentialSecretGuardTest scans this tree). Outcome is a CONTROLLED enum (no free-text reason) so there is no secret-leak avenue. The future UI-P2 caller maps the exec write outcome into this request and fires it on the dedicated per-tenant credential hash chain (strategy_id sentinel '_broker'). DARK in P6-d: the BrokerCredentialAuditActivities.record Activity is registered on the orchestrator-core worker but has no caller.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: conint(ge=1)
    """
    DTO contract version. See CopytradeSignalPayload.schema_version.
    """
    tenant_id: constr(min_length=1)
    """
    Tenant whose broker credential was written/rotated. Subject key and the audit event's tenant_id; the per-tenant credential chain is keyed on tenant_id + the '_broker' strategy sentinel.
    """
    provider: constr(min_length=1)
    """
    Broker provider the credential targets (e.g. 'alpaca'). A plain non-secret string, NOT the broker_target enum, to avoid the regen.sh BrokerTarget dedup collision.
    """
    change_type: ChangeType
    """
    Whether this credential write created the first credential for the tenant/provider row (CREATE) or rotated an existing one (ROTATE).
    """
    outcome: Outcome
    """
    Controlled disposition of the write. A closed enum (no free-text reason) so the audit subject can never carry leaked key material. On any REJECTED_* outcome the optional broker_account_id/credential_version/kek_version are typically omitted.
    """
    actor: constr(min_length=1)
    """
    Who/what caused the credential write (e.g. an api-gateway route or operator id). Subject key and the audit event's actor.
    """
    occurred_at: AwareDatetime
    """
    When the credential write/rotation occurred (RFC 3339 / ISO-8601). Becomes the audit event's occurred_at.
    """
    broker_account_id: constr(min_length=1) | None = None
    """
    OPTIONAL. The NON-SECRET brokerage account number returned by the /v2/account identity probe (e.g. 'PA3FKGPFYPLH'). Omitted on rejected outcomes. NOT a key/secret.
    """
    credential_version: conint(ge=1) | None = None
    """
    OPTIONAL. The persisted credential row version after the write (the CAS-bumped version). Omitted on rejected outcomes.
    """
    kek_version: conint(ge=1) | None = None
    """
    OPTIONAL. The KEK version used to wrap the row DEK at write time. A non-secret version identifier, never the KEK bytes. Omitted on rejected outcomes.
    """
    correlation_id: str | None = None
    """
    OPTIONAL cross-event correlation key (e.g. the request id of the originating write).
    """
