# generated by datamodel-codegen:
#   filename:  copytrade-signal-payload.json
#   timestamp: 2026-05-13T23:26:33+00:00

from __future__ import annotations

from datetime import date
from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, ConfigDict, PositiveFloat, conint, constr


class Action(StrEnum):
    """
    Author intent: buy-to-open, sell-to-close, or retrospective average-note.
    """

    bto = "BTO"
    stc = "STC"
    avg = "AVG"


class Right(StrEnum):
    """
    Option right: Call or Put.
    """

    c = "C"
    p = "P"


class CopytradeSignalPayload(BaseModel):
    """
    Parsed Discord BTO/STC/AVG line emitted by signal-source-discord and consumed by CopytradeSignalWorkflow. Reference: docs/plans/PLAN.md, oh-my-opentrade/backend/internal/domain/copytrade.go.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: conint(ge=1)
    """
    DTO contract version. Workers reject newer-than-build inputs to force orchestrator rollback. Start at 1; bump when fields change in non-backward-compatible ways.
    """
    tenant_id: constr(min_length=1)
    """
    Tenant scope key. Required on every Activity payload and workflow input.
    """
    strategy_id: constr(min_length=1)
    """
    Strategy scope key within the tenant.
    """
    signal_id: constr(min_length=1)
    """
    Deterministic dedupe key. Shape: '<message_id>:<line_index>'.
    """
    message_id: constr(min_length=1)
    """
    Discord message id the line was parsed from.
    """
    author: constr(min_length=1)
    """
    Discord username that posted the line.
    """
    posted_at: AwareDatetime
    """
    RFC3339 UTC timestamp when the message was posted on Discord (source-of-truth: sidecar from Discord DOM).
    """
    action: Action
    """
    Author intent: buy-to-open, sell-to-close, or retrospective average-note.
    """
    ticker: constr(pattern=r"^[A-Z]{1,6}$")
    """
    Underlying equity symbol; uppercase, no exchange suffix.
    """
    expiry: date
    """
    Option expiry date (YYYY-MM-DD) at 00:00 UTC of that calendar date.
    """
    strike: PositiveFloat
    """
    Strike price, dollars.
    """
    right: Right
    """
    Option right: Call or Put.
    """
    price: PositiveFloat
    """
    Author's stated fill premium (per contract, dollars). 5-30s stale by the time we read it; size off fresh ask not this.
    """
    tail: str | None = None
    """
    Raw trailing text after the parsed grammar (e.g., 'half out', 'partial'). Empty string if none.
    """
    raw_line: constr(min_length=1)
    """
    The line as parsed, for audit.
    """
