# generated by datamodel-codegen:
#   filename:  copytrade-derisk-payload.json

from __future__ import annotations

from decimal import Decimal
from typing import Annotated

from datetime import date
from enum import StrEnum

from pydantic import Field, AwareDatetime, BaseModel, ConfigDict, conint, constr


class Right(StrEnum):
    """
    Option right of the attributed target BTO: Call or Put.
    """

    c = "C"
    p = "P"


class CopytradeDeriskPayload(BaseModel):
    """
    De-risk instruction emitted by signal-source-discord when an author follows a BTO with a separate free-form 'de-risk' message (a '0-or-hero' family cue such as '0 or hero' / 'zero or hero', or 'use your own stop') that carries NO BTO/STC/AVG grammar. The sidecar attributes the cue to that same author's preceding BTO (ticker-aware, bounded look-back) and emits this payload per subscribing tenant, carrying the resolved target (ticker, expiry, strike, right) — NOT the OCC option symbol, which CopytradeDeriskWorkflow resolves downstream via ContractActivities.resolve, identical to the BTO path. The workflow trims the open position to a keep-fraction and arms the chandelier trailing stop on the remainder. See docs/plans/PLAN-2026-08-04-copytrade-derisk-followup-cue.md.
    """

    model_config = ConfigDict(
        extra="forbid",
        json_encoders={Decimal: float},
    )
    schema_version: conint(ge=1)
    """
    DTO contract version. See CopytradeSignalPayload.schema_version.
    """
    tenant_id: constr(min_length=1)
    """
    Tenant scope key. Required on every Activity payload and workflow input.
    """
    strategy_id: constr(min_length=1)
    """
    Strategy scope key within the tenant.
    """
    signal_id: constr(min_length=1)
    """
    Deterministic dedupe key for this de-risk event. Shape: '<cue_message_id>:derisk'. Distinct from any BTO/STC signal_id so the position workflow's exit-dedup never collides.
    """
    message_id: constr(min_length=1)
    """
    Discord message id of the de-risk cue message.
    """
    author: constr(min_length=1)
    """
    Discord username that posted the de-risk cue (must match the author of the attributed BTO).
    """
    posted_at: AwareDatetime
    """
    RFC3339 UTC timestamp when the cue message was posted on Discord.
    """
    ticker: constr(pattern=r"^[A-Z]{1,6}$")
    """
    Underlying equity ticker of the attributed target BTO (uppercase, no exchange suffix). RAW underlying — the OCC symbol is composed downstream by ContractActivities.resolve from (ticker, expiry, strike, right).
    """
    expiry: date
    """
    Option expiry date (YYYY-MM-DD) of the attributed target BTO.
    """
    strike: Annotated[Decimal, Field(gt=0)]
    """
    Strike price (dollars) of the attributed target BTO.
    """
    right: Right
    """
    Option right of the attributed target BTO: Call or Put.
    """
    target_bto_signal_id: constr(min_length=1)
    """
    signal_id of the attributed preceding BTO line, for audit correlation between the de-risk action and the original entry.
    """
    target_entry_premium: Annotated[Decimal, Field(gt=0)] | None = None
    """
    Optional. The attributed BTO's stated fill premium, used only to seed the chandelier trail's initial peak at arm time (it ratchets up on live ticks regardless). Null/absent: the trail seeds its peak from the first live tick.
    """
    matched_cue: str | None = None
    """
    Optional. The normalized cue phrase that fired (e.g. '0 or hero'), recorded for audit. Null/absent: not surfaced.
    """
    raw_line: constr(min_length=1)
    """
    The de-risk cue message text as observed, for audit.
    """
