# generated by datamodel-codegen:
#   filename:  copytrade-signal-payload.json

from __future__ import annotations

from decimal import Decimal
from typing import Annotated

from datetime import date
from enum import StrEnum

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    confloat,
    conint,
    constr,
)


class Action(StrEnum):
    """
    Author intent: buy-to-open, sell-to-close, or retrospective average-note.
    """

    bto = "BTO"
    stc = "STC"
    avg = "AVG"


class Right(StrEnum):
    """
    Option right: Call or Put.
    """

    c = "C"
    p = "P"


class CloseIntent(StrEnum):
    """
    Optional classifier hint for STC lines: whether the author intends a full exit or a partial. Null/absent = unclassified. Spec-only in Phase 1 (PLAN-2026-07-25-stc-intent-classifier); no consumer yet — the orchestrator STC-intent enforcement lands in a later phase, gated per-tenant.
    """

    full = "full"
    partial = "partial"


class CopytradeSignalPayload(BaseModel):
    """
    Parsed Discord BTO/STC/AVG line emitted by signal-source-discord and consumed by CopytradeSignalWorkflow. Carries the underlying ticker plus the (expiry, strike, right) tuple — NOT the resolved OCC option symbol. OCC resolution (e.g. 'AAPL250117C00150000') is performed downstream by ContractActivities.resolve and surfaces on OrderIntent.option_symbol / PreTradeCheckRequest.option_symbol. Reference: docs/plans/PLAN.md, oh-my-opentrade/backend/internal/domain/copytrade.go.
    """

    model_config = ConfigDict(
        extra="forbid",
        json_encoders={Decimal: float},
    )
    schema_version: conint(ge=1)
    """
    DTO contract version. Workers reject newer-than-build inputs to force orchestrator rollback. Start at 1; bump when fields change in non-backward-compatible ways.
    """
    tenant_id: constr(min_length=1)
    """
    Tenant scope key. Required on every Activity payload and workflow input.
    """
    strategy_id: constr(min_length=1)
    """
    Strategy scope key within the tenant.
    """
    signal_id: constr(min_length=1)
    """
    Deterministic dedupe key. Shape: '<message_id>:<line_index>'.
    """
    message_id: constr(min_length=1)
    """
    Discord message id the line was parsed from.
    """
    author: constr(min_length=1)
    """
    Discord username that posted the line.
    """
    posted_at: AwareDatetime
    """
    RFC3339 UTC timestamp when the message was posted on Discord (source-of-truth: sidecar from Discord DOM).
    """
    action: Action
    """
    Author intent: buy-to-open, sell-to-close, or retrospective average-note.
    """
    ticker: constr(pattern=r"^[A-Z]{1,6}$")
    """
    Underlying equity ticker (e.g. 'AAPL'); uppercase, no exchange suffix. This is the RAW underlying — not an OCC option symbol. The full OCC symbol (e.g. 'AAPL250117C00150000') is composed downstream by ContractActivities.resolve from (ticker, expiry, strike, right) and lands on OrderIntent.option_symbol before exec.
    """
    expiry: date
    """
    Option expiry date (YYYY-MM-DD) at 00:00 UTC of that calendar date.
    """
    strike: Annotated[Decimal, Field(gt=0)]
    """
    Strike price, dollars.
    """
    right: Right
    """
    Option right: Call or Put.
    """
    price: Annotated[Decimal, Field(gt=0)]
    """
    Author's stated fill premium (per contract, dollars). 5-30s stale by the time we read it; size off fresh ask not this.
    """
    tail: str | None = None
    """
    Raw trailing text after the parsed grammar (e.g., 'half out', 'partial'). Empty string if none.
    """
    close_intent: CloseIntent | None = None
    """
    Optional classifier hint for STC lines: whether the author intends a full exit or a partial. Null/absent = unclassified. Spec-only in Phase 1 (PLAN-2026-07-25-stc-intent-classifier); no consumer yet — the orchestrator STC-intent enforcement lands in a later phase, gated per-tenant.
    """
    close_confidence: confloat(ge=0.0, le=1.0) | None = None
    """
    Optional confidence score in [0,1] for close_intent. Null/absent = no score. Spec-only in Phase 1; no consumer yet.
    """
    raw_line: constr(min_length=1)
    """
    The line as parsed, for audit.
    """
