# generated by datamodel-codegen:
#   filename:  correct-booked-lot-request.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class CorrectBookedLotRequest(BaseModel):
    """
    Update payload for PositionWorkflow.correct_booked_lot (#820) — the OPERATOR lever that raises an under-booked entry lot to the broker journal's FILLED truth (the 2026-08-25 sliced-fill incident: booked 2 of 21). Implemented as a thin front-end over the #738 bookEntryGrowth delta arithmetic — it raises expected_qty then books delta = qty - entryBookedQty, incrementing entryBookedQty AND remainingQty together; it NEVER assigns remainingQty absolutely (a position with booked partial exits would re-add sold contracts and over-sell on the next close — the 2026-08-17 AMD near-miss class). The handler cross-checks the requested qty against the exec journal's FILLED row for the entry order and fails closed when the journal cannot confirm it; the operator's number is a confirmation, not the source of truth. An Update rather than a signal because a refusal (journal mismatch, position already exiting, trail armed) must be REPORTED — a silently dropped correction leaves the operator believing a real-money lot is tracked when it is not.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: int
    """
    Payload schema version; 1.
    """
    qty: int
    """
    The corrected TOTAL entry qty (the journal FILLED truth, e.g. 21) — not a delta. Must exceed the currently booked entry qty (downward corrections are exits, not corrections) and must be confirmed by the exec journal row before any state changes.
    """
    operator_id: str
    """
    The operator performing the correction; recorded as actor operator:<id> on the PositionLotCorrected audit row.
    """
    reason: str
    """
    Why the correction is being applied (e.g. 'sliced-fill under-booking 2026-08-25, plan P4'). Recorded verbatim in the audit row.
    """
