# generated by datamodel-codegen:
#   filename:  disarm-trail-request.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class DisarmTrailRequest(BaseModel):
    """
    Update payload for PositionWorkflow.disarm_trail (#825) — the operator lever that removes an armed trailing stop WITHOUT closing the position, so its basis can be re-anchored (the #820 runbook order: disarm → correct_booked_lot → re-arm; armTrail is deliberately idempotent and will never re-anchor an armed trail). Disarming removes real-money downside protection: the reason is mandatory and the TrailDisarmed audit row PAGES. An Update, not a signal — a refusal (nothing armed) must be reported, and the synchronous answer carries the prior stop so the operator knows exactly what protection was just removed. The premium-tick subscription is left running (no unsubscribe activity exists; ticks are ignored while disarmed and a re-arm reuses the stream).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: int
    """
    Payload schema version; 1.
    """
    operator_id: str
    """
    The operator disarming; recorded as actor operator:<id> on the paged TrailDisarmed audit row.
    """
    reason: str
    """
    Why protection is being removed (e.g. 'disarm-correct-rearm, #820 heal'). Mandatory; recorded verbatim.
    """
