# generated by datamodel-codegen:
#   filename:  equity-tick.json

from __future__ import annotations

from decimal import Decimal
from typing import Annotated

from pydantic import Field, AwareDatetime, BaseModel, ConfigDict, conint, constr


class EquityTick(BaseModel):
    """
    Phase 2 (watchlist-trigger): a single real-time observation of an underlying equity's last trade. Streamed from market-data-svc and signalled into WatchlistTriggerWorkflow (signal_name, default equityTick). retrieved_at is the wire-time stamp from the source feed. stale is set when the source flagged the print halted/old; a consumer MUST NOT drive a level trigger off a stale tick.
    """

    model_config = ConfigDict(
        extra="forbid",
        json_encoders={Decimal: float},
    )
    schema_version: conint(ge=1)
    """
    DTO contract version.
    """
    ticker: constr(min_length=1)
    """
    Underlying equity symbol the tick is for.
    """
    last: Annotated[Decimal, Field(gt=0)]
    """
    Last trade price of the underlying, dollars. Source-of-truth field for the level-trigger comparison.
    """
    retrieved_at: AwareDatetime
    """
    RFC3339 UTC timestamp when the tick was observed by the source feed.
    """
    stale: bool
    """
    True when the source flagged the print as halted/stale. Stale ticks are never emitted by SubscribeEquityActivity, so consumers should normally see false; the field exists so a future emit-on-stale policy stays explicit.
    """
