# generated by datamodel-codegen:
#   filename:  fill-signal-payload.json

from __future__ import annotations

from decimal import Decimal
from typing import Annotated

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    conint,
    constr,
)


class FillSignalPayload(BaseModel):
    """
    Wire shape signalled from exec-svc to the orchestrator's CopytradeSignalWorkflow.onFill / PositionWorkflow.onFill handlers when the broker reports a fill. Field names are camelCase to match the Temporal data converter's default Jackson naming, so workflows in flight at deploy time deserialise without drift.
    """

    model_config = ConfigDict(
        extra="forbid",
        json_encoders={Decimal: float},
    )
    broker_order_id: constr(min_length=1) = Field(..., alias="brokerOrderId")
    """
    Broker-assigned order identifier the fill is reported against. Matches OrderIntentJournal.broker_order_id for the originating intent.
    """
    filled_qty: conint(ge=0) = Field(..., alias="filledQty")
    """
    Cumulative filled quantity reported by the broker for this order.
    """
    avg_fill_price: Annotated[Decimal, Field(gt=0)] = Field(..., alias="avgFillPrice")
    """
    Average fill price across all partials reported for this order.
    """
    filled_at: AwareDatetime = Field(..., alias="filledAt")
    """
    Broker timestamp of the fill report (ISO-8601 with offset).
    """
