# generated by datamodel-codegen:
#   filename:  fire-decision.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class FireDecision(BaseModel):
    """
    Outcome of the fire gate for an armed watchlist trigger: whether to proceed with the entry and at what size multiplier. Returned by the fire-decision step toward the trigger-strategy workflow.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    proceed: bool
    """
    True to proceed with the entry; false to hold (the trigger stays armed for later evaluation).
    """
    size_multiplier: Annotated[float, Field(ge=0.0)]
    """
    Position-size multiplier applied to the base allocation for this fire. 0 suppresses the entry without disarming.
    """
    reason: str | None = None
    """
    Optional human-readable reason for the fire decision (audit).
    """
