# generated by datamodel-codegen:
#   filename:  force-close-request.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class ForceCloseRequest(BaseModel):
    """
    Update payload for PositionWorkflow.force_close. Validator checks operator_id is non-empty. Handler cancels any in-flight exit, then places a marketable-to-bid SELL for the full remaining qty (no floor in v0/paper). If remainingQty == 0 after cancel-ack, the handler audits ForceCloseNoop and returns. WaitPolicy=Accepted: HTTP 202 returns immediately with the new exit_signal_id; operator polls position_state for completion.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Annotated[int, Field(ge=1)]
    operator_id: Annotated[str, Field(min_length=1)]
    reason: Annotated[str, Field(min_length=1)]
    """
    Free-form operator-supplied reason recorded on ForceCloseRequested audit event.
    """
