# generated by datamodel-codegen:
#   filename:  get-option-quote-request.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, conint, constr


class GetOptionQuoteRequest(BaseModel):
    """
    Plan-2A R-AA-2: request from PositionWorkflow to market-data-svc for a one-shot NBBO snapshot of an option contract. The snapshot anchors bounded scheduled-flatten sells (eod/expiry/chandelier) on a real live bid instead of a market order. Pure read; mirrors SubscribePremiumRequest's tenant/strategy scoping.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: conint(ge=1)
    """
    DTO contract version.
    """
    tenant_id: constr(min_length=1)
    strategy_id: constr(min_length=1)
    contract_symbol: constr(min_length=1)
    """
    OCC option symbol to snapshot.
    """
