# generated by datamodel-codegen:
#   filename:  journal-entry.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


from ohmytradeagent_contract.types.broker_target import BrokerTarget


class Side(StrEnum):
    buy = "BUY"
    sell = "SELL"


class State(StrEnum):
    recorded = "RECORDED"
    submitted = "SUBMITTED"
    filled = "FILLED"
    cancelled = "CANCELLED"
    expired = "EXPIRED"
    errored = "ERRORED"


class JournalEntry(BaseModel):
    """
    Snapshot of one OrderIntentJournal row, returned by exec.journal_dump_open Activity to ReconciliationWorkflow. Only non-terminal entries (RECORDED, SUBMITTED) are dumped.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Annotated[int, Field(ge=1)]
    intent_key: Annotated[str, Field(min_length=1)]
    signal_id: Annotated[str, Field(min_length=1)]
    tenant_id: Annotated[str, Field(min_length=1)]
    strategy_id: Annotated[str, Field(min_length=1)]
    broker_target: BrokerTarget
    client_order_id: Annotated[str, Field(min_length=1)]
    option_symbol: Annotated[str, Field(min_length=1)]
    side: Side
    qty: Annotated[int, Field(ge=1)]
    state: State
    broker_order_id: str | None = None
    recorded_at: AwareDatetime
    submitted_at: AwareDatetime | None = None
