# generated by datamodel-codegen:
#   filename:  journal-entry.json

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, ConfigDict, conint, constr


class BrokerTarget(StrEnum):
    paper = "paper"
    live = "live"
    alpaca_paper = "alpaca-paper"
    alpaca_live = "alpaca-live"
    tradier_paper = "tradier-paper"
    tradier_live = "tradier-live"
    ibkr_paper = "ibkr-paper"
    ibkr_live = "ibkr-live"
    schwab_paper = "schwab-paper"
    schwab_live = "schwab-live"


class Side(StrEnum):
    buy = "BUY"
    sell = "SELL"


class State(StrEnum):
    recorded = "RECORDED"
    submitted = "SUBMITTED"
    filled = "FILLED"
    cancelled = "CANCELLED"
    expired = "EXPIRED"
    errored = "ERRORED"


class JournalEntry(BaseModel):
    """
    Snapshot of one OrderIntentJournal row, returned by exec.journal_dump_open Activity to ReconciliationWorkflow. Only non-terminal entries (RECORDED, SUBMITTED) are dumped.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: conint(ge=1)
    intent_key: constr(min_length=1)
    signal_id: constr(min_length=1)
    tenant_id: constr(min_length=1)
    strategy_id: constr(min_length=1)
    broker_target: BrokerTarget
    client_order_id: constr(min_length=1)
    option_symbol: constr(min_length=1)
    side: Side
    qty: conint(ge=1)
    state: State
    broker_order_id: str | None = None
    recorded_at: AwareDatetime
    submitted_at: AwareDatetime | None = None
