# generated by datamodel-codegen:
#   filename:  kill-switch-workflow-input.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, conint, constr


class KillSwitchWorkflowInput(BaseModel):
    """
    Input for KillSwitchWorkflow (Phase 5). One workflow per (tenant_id, strategy_id), bootstrapped on orchestrator startup. Long-running; no continueAsNew in v0 (history is small — handful of state changes per day).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: conint(ge=1)
    """
    DTO contract version. Workers reject newer-than-build inputs.
    """
    tenant_id: constr(min_length=1)
    strategy_id: constr(min_length=1)
