# generated by datamodel-codegen:
#   filename:  kill-switch-workflow-input.json

from __future__ import annotations

from datetime import date
from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class KillSwitchWorkflowInput(BaseModel):
    """
    Input for KillSwitchWorkflow (Phase 5). One workflow per (tenant_id, strategy_id), bootstrapped on orchestrator startup. Long-running; the workflow now invokes continueAsNew once history-length crosses a watermark (issue #124) and carries the optional state fields below across the boundary. Fresh bootstrap inputs omit the carry-forward fields; replayed continueAsNew inputs populate them.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Annotated[int, Field(ge=1, le=2)]
    """
    DTO contract version. v1 = bootstrap-only input; v2 adds optional carry-forward fields produced by continueAsNew. Workers reject newer-than-build inputs.
    """
    tenant_id: Annotated[str, Field(min_length=1)]
    strategy_id: Annotated[str, Field(min_length=1)]
    tripped: bool | None = None
    """
    Carry-forward state from a prior run. Absent on fresh bootstrap. Default false.
    """
    reason: str | None = None
    """
    Carry-forward trip reason from a prior run. Absent on fresh bootstrap.
    """
    actor: str | None = None
    """
    Carry-forward trip actor from a prior run. Absent on fresh bootstrap.
    """
    tripped_at: AwareDatetime | None = None
    """
    Carry-forward trip timestamp from a prior run. Absent on fresh bootstrap.
    """
    cooling_down_until: AwareDatetime | None = None
    """
    Carry-forward reset cooldown deadline from a prior run. Absent on fresh bootstrap.
    """
    trading_day: date | None = None
    """
    Carry-forward trading day from a prior run. Absent on fresh bootstrap; next heartbeat refreshes via calendar.todayEt().
    """
