# generated by datamodel-codegen:
#   filename:  killswitch-state.json

from __future__ import annotations

from datetime import date
from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class KillSwitchState(BaseModel):
    """
    Result of KillSwitchWorkflow.killswitch_state query. Consumed by risk.check_entry (workflow-not-found and other non-Success outcomes → fail closed at the call site with KILL_SWITCH_UNAVAILABLE).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Annotated[int, Field(ge=1)]
    tripped: bool
    """
    True iff the switch is currently active (trips block new entries; cool-down after reset is reported via cooling_down_until).
    """
    reason: str | None = None
    """
    Trip reason when tripped=true. Empty when never tripped or reset.
    """
    actor: str | None = None
    """
    Who/what tripped (e.g., 'operator:ridopark', 'auto:daily_loss').
    """
    tripped_at: AwareDatetime | None = None
    """
    RFC3339 UTC trip timestamp. Null when never tripped or after a reset.
    """
    cooling_down_until: AwareDatetime | None = None
    """
    After reset, new entries are blocked with KILL_SWITCH_COOLING_DOWN until this timestamp. Null when not in cool-down.
    """
    trading_day: date | None = None
    """
    Current trading day the auto-trip heartbeat is evaluating (America/New_York).
    """
    open_positions: Annotated[int | None, Field(ge=0)] = None
    """
    Account-cap open-position count (listed) from the last heartbeat's open-book read. Null for the per-strategy kill switch (only the AccountKillSwitchWorkflow populates it). Advisory/observability only.
    """
    open_mtm: float | None = None
    """
    Account-cap unrealized open P&L ((liveBid-entry)*qty*100) from the last heartbeat, when the book was fully priceable; null when unpriceable or per-strategy. SIGNED (a gain is positive) - NOT a loss amount and NOT position value.
    """
