# generated by datamodel-codegen:
#   filename:  live-deactivation-request.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


from ohmytradeagent_contract.types.broker_target import BrokerTarget


class LiveDeactivationRequest(BaseModel):
    """
    Phase F (operator-account-onboarding): input to LiveActivationWorkflow.deactivateLive. A server-side one-click live-DEACTIVATION request, machine-attributed to the authenticated operator. The workflow emits a LivePromotionDeactivated row (invalidating the prior approval so the order-time gate fails closed) AND trips the per-(tenant, strategy) kill switch. Carries ZERO key material.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Annotated[int, Field(ge=1)]
    """
    DTO contract version. See CopytradeSignalPayload.schema_version.
    """
    tenant_id: Annotated[str, Field(min_length=1)]
    """
    The tenant whose (tenant, strategy) live promotion is being deactivated.
    """
    strategy_id: Annotated[str, Field(min_length=1)]
    """
    The strategy being deactivated.
    """
    broker_target: BrokerTarget
    """
    The live broker_target being deactivated. Recorded in the LivePromotionDeactivated subject (the gate matches subject->>'broker_target' newest-after-approval).
    """
    operator_id: Annotated[str, Field(min_length=1)]
    """
    The authenticated operator (X-Operator-Id) performing the deactivation. Recorded in the emitted LivePromotionDeactivated subject (operator_id).
    """
