# generated by datamodel-codegen:
#   filename:  live-promotion-approval-request.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, conint, constr


class LivePromotionApprovalRequest(BaseModel):
    """
    Operator-issued dual-control sign-off recording a Phase 7 promotion to a *-live broker adapter. Validator rejects same-approver (approver_id_1 == approver_id_2) or blank IDs with error code approvers_must_differ. Emits exactly one LivePromotionApproved audit event when validation passes. See docs/ops/live-promotion-rollback.md §Sign-off recording. This PR only records the sign-off; the broker_target ConfigMap flip is still operator-driven post-sign-off.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: conint(ge=1)
    approver_id_1: constr(min_length=1)
    approver_id_2: constr(min_length=1)
    tenant_id: constr(min_length=1)
    strategy_id: constr(min_length=1)
    broker_target: constr(min_length=1)
    """
    Target *-live broker adapter the promotion is signed-off against (e.g. 'tradier-live').
    """
    note: str | None = None
    """
    Operator-supplied free-form note recorded in the LivePromotionApproved audit event subject.
    """
