# generated by datamodel-codegen:
#   filename:  live-activation-request.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


from ohmytradeagent_contract.types.broker_target import BrokerTarget


class LiveActivationRequest(BaseModel):
    """
    Phase F (operator-account-onboarding): input to LiveActivationWorkflow.activateLive. A server-side one-click live-activation request, machine-attributed to the authenticated operator. The workflow runs a fail-closed required-config gate + a fresh account probe and, on pass, emits a fresh LivePromotionApproved row (the gate-readable kind) so the already-wired order-time live-promotion gate keeps firing. Carries ZERO key material — credentials are resolved per-tenant by exec-svc at order time, never threaded through this request.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Annotated[int, Field(ge=1)]
    """
    DTO contract version. See CopytradeSignalPayload.schema_version.
    """
    tenant_id: Annotated[str, Field(min_length=1)]
    """
    The tenant whose (tenant, strategy) live promotion is being activated.
    """
    strategy_id: Annotated[str, Field(min_length=1)]
    """
    The strategy being activated for live trading.
    """
    broker_target: BrokerTarget
    """
    The live broker_target being approved. Recorded in the LivePromotionApproved subject (the gate matches subject->>'broker_target') and used to route the fresh account probe to broker-<value>.
    """
    operator_id: Annotated[str, Field(min_length=1)]
    """
    The authenticated operator (X-Operator-Id) performing the one-click activation. Recorded as the machine-attributed approver in the emitted LivePromotionApproved subject (operator_id) — the single-operator substitute for the legacy dual-control approve().
    """
    expected_account_id: str | None = None
    """
    OPTIONAL. NOT supplied by the api-gateway caller — set by LiveActivationWorkflow after the fresh account probe (the probed brokerage account_number) and threaded into LivePromotionActivities.activate so it lands in the LivePromotionApproved subject (expected_account_id). Absent on the inbound request; populated server-side post-probe.
    """
