# generated by datamodel-codegen:
#   filename:  order-intent.json

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, ConfigDict, PositiveFloat, conint, constr


class BrokerTarget(StrEnum):
    """
    Routes the activity to the broker-paper or broker-live task queue. Phase 2b only handles 'paper'.
    """

    paper = "paper"
    live = "live"


class Side(StrEnum):
    """
    BUY=BTO; SELL=STC. Phase 2b only exercises BUY.
    """

    buy = "BUY"
    sell = "SELL"


class OrderIntent(BaseModel):
    """
    Workflow→exec-svc request to place a paper or live broker order. Generated by CopytradeSignalWorkflow after risk+contract gates pass and consumed by ExecActivities.placeOrder on the broker-<env> task queue. intent_key drives the 3-layer idempotency model (plan line 362).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: conint(ge=1)
    """
    DTO contract version. Workers reject newer-than-build inputs to force redeploy.
    """
    tenant_id: constr(min_length=1)
    strategy_id: constr(min_length=1)
    intent_key: constr(min_length=1)
    """
    Deterministic idempotency key shared with broker client_order_id. Shape: '<workflow_id>:entry' or '<workflow_id>:exit:<exit_signal_id>'.
    """
    signal_id: constr(min_length=1)
    """
    Source Discord signal_id (correlates to CopytradeSignalPayload.signal_id and the audit-log correlation_id).
    """
    broker_target: BrokerTarget
    """
    Routes the activity to the broker-paper or broker-live task queue. Phase 2b only handles 'paper'.
    """
    option_symbol: constr(min_length=1)
    """
    OCC option symbol (resolved by ContractActivities.resolve).
    """
    side: Side
    """
    BUY=BTO; SELL=STC. Phase 2b only exercises BUY.
    """
    qty: conint(ge=1)
    """
    Number of contracts (after capital-weight clamp).
    """
    limit_price: PositiveFloat | None = None
    """
    Optional limit. Omitted (null) means marketable-mid. Phase 2b passes payload.price.
    """
    recorded_at: AwareDatetime
    """
    Workflow's view of when the intent was minted (UTC).
    """
