# generated by datamodel-codegen:
#   filename:  partial-exit-request.json

from __future__ import annotations

from decimal import Decimal
from typing import Annotated

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    confloat,
    conint,
    constr,
)


class PartialExitRequest(BaseModel):
    """
    Signal payload to PositionWorkflow.partial_exit. Dispatched by CopytradeSignalWorkflow STC branch after KeywordPartialMatcher resolves the fraction. signal_id is the dedupe key inside the position.
    """

    model_config = ConfigDict(
        extra="forbid",
        json_encoders={Decimal: float},
    )
    schema_version: conint(ge=1)
    """
    DTO contract version. See CopytradeSignalPayload.schema_version.
    """
    tenant_id: constr(min_length=1)
    strategy_id: constr(min_length=1)
    signal_id: constr(min_length=1)
    """
    Dedupe key inside the receiving PositionWorkflow. Shape: '<message_id>:<line_index>'.
    """
    position_workflow_id: constr(min_length=1)
    """
    Target PositionWorkflow workflow_id (resolved via Redis cache + Visibility fallback).
    """
    fraction: confloat(le=1.0, gt=0.0)
    """
    Fraction of remaining qty to close. Resolved from KeywordPartialMatcher.match(tail, cfg.partial_fractions, cfg.default_stc_fraction).
    """
    ref_premium: Annotated[Decimal, Field(gt=0)]
    """
    Author-posted exit premium (for audit; not source-of-truth for fill price).
    """
    reason: constr(min_length=1)
    """
    Why the exit fired (e.g., 'stc_signal').
    """
    author: constr(min_length=1)
    """
    Discord author who posted the STC line.
    """
    raw_line: constr(min_length=1)
    """
    The STC line as parsed, for audit.
    """
    occurred_at: AwareDatetime
    """
    RFC3339 UTC timestamp when the signal was emitted (sidecar source-of-truth).
    """
