# generated by datamodel-codegen:
#   filename:  partial-close-request.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, confloat, conint, constr


class PartialCloseRequest(BaseModel):
    """
    Update payload for PositionWorkflow.partial_close — the operator-initiated partial exit ('Trim') from the dashboard /live holdings table. Validator checks operator_id and reason are non-empty and that fraction is in (0,1) EXCLUSIVE: a trim is reduce-only by construction, so a full close must go through force_close instead. The handler enqueues a synthetic PartialExitRequest (market=true) onto the SAME pendingExits deque the STC path uses, so the trim inherits every existing partial-exit safeguard (qty ceil against live remainingQty, min-partial-qty behavior, dedupe, fill booking into realized P&L). WaitPolicy=Accepted: HTTP 202 returns immediately with the new exit_signal_id.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: conint(ge=1)
    operator_id: constr(min_length=1)
    reason: constr(min_length=1)
    """
    Free-form operator-supplied reason recorded on the OperatorTrimRequested audit event.
    """
    fraction: confloat(lt=1.0, gt=0.0)
    """
    Fraction of the remaining qty to sell. The workflow closes min(remainingQty, ceil(remainingQty * fraction)) contracts, matching the STC partial math exactly. Strictly < 1 so a trim can never be a full close.
    """
