# generated by datamodel-codegen:
#   filename:  position-workflow-input.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, PositiveFloat, conint, constr


class PositionWorkflowInput(BaseModel):
    """
    Input to PositionWorkflow at start. Phase 0 ships the DTO slot; the workflow body lands in Phase 3.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: conint(ge=1)
    tenant_id: constr(min_length=1)
    strategy_id: constr(min_length=1)
    entry_signal_id: constr(min_length=1)
    """
    signal_id of the BTO that opened the position. Disambiguates re-BTO on the same OCC under WorkflowIDReusePolicy.REJECT_DUPLICATE.
    """
    contract_symbol: constr(min_length=1)
    """
    OCC option symbol (e.g., NVDA250516C00140000). Set as a Search Attribute 'ContractSymbol' on workflow start for STC dispatch.
    """
    qty: conint(ge=1)
    """
    Original position size, contracts.
    """
    entry_premium: PositiveFloat
    """
    Fill premium per contract, dollars (source-of-truth: broker fill, not author-posted price).
    """
    source_signal_workflow_id: str | None = None
    """
    Workflow ID of the CopytradeSignalWorkflow that spawned this position. Optional; useful for cross-workflow audit correlation.
    """
