# generated by datamodel-codegen:
#   filename:  position-snapshot-request.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


from ohmytradeagent_contract.types.broker_target import BrokerTarget


class PositionSnapshotRequest(BaseModel):
    """
    Dashboard live-marks input. The tenant-dashboard BFF (a Temporal CLIENT, which cannot dispatch an Activity directly) starts the short-lived PositionSnapshotWorkflow with this request; the workflow dispatches ReconciliationExecActivity.brokerListOpenPositions to the broker-<broker_target> task queue and returns the broker-held positions WITH their live marks (current_price / unrealized_pl / unrealized_intraday_pl). Mirrors AccountSnapshotRequest. The marks are account-level broker truth (shared across tenants on a broker_target), never a risk-gate input — tenant_id/strategy_id are forward-compat filter hooks the single-account Alpaca adapter ignores today.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Annotated[int, Field(ge=1)]
    """
    DTO contract version. See CopytradeSignalPayload.schema_version.
    """
    broker_target: BrokerTarget
    """
    Routes the brokerListOpenPositions Activity to the broker-<value> task queue, mirroring AccountSnapshotRequest.broker_target.
    """
    tenant_id: str | None = None
    """
    Optional forward-compat filter hook passed through to brokerListOpenPositions. The single-account Alpaca adapter ignores it today (positions are account-level); future multi-account brokers will filter on it.
    """
    strategy_id: str | None = None
    """
    Optional forward-compat filter hook passed through to brokerListOpenPositions. Ignored by the single-account Alpaca adapter today.
    """
    correlation_id: str | None = None
    """
    Optional cross-event correlation key for tracing the dashboard read.
    """
