# generated by datamodel-codegen:
#   filename:  position-workflow-input.json

from __future__ import annotations

from decimal import Decimal
from typing import Annotated

from enum import StrEnum

from pydantic import Field, BaseModel, ConfigDict, conint, constr


from ohmytradeagent_contract.types.broker_target import BrokerTarget


class MinPartialQtyBehavior(StrEnum):
    """
    Issue #205: carried over from the spawning CopytradeSignalWorkflow's StrategyConfig.min_partial_qty_behavior. Drives PositionWorkflow.processOne's pre-qtyToClose gate when remainingQty <= 1 AND floor(remainingQty * fraction) == 0. 'skip' emits PartialExitSkippedMinQty and places no order; 'full_close' closes the last contract. Optional/null treated as 'skip' to match the YAML comment's documented default. Gated behind Workflow.getVersion('min-partial-qty-skip', DEFAULT, 1) so in-flight pre-#205 workflows preserve legacy ceil(remainingQty * fraction) behavior on replay.
    """

    skip = "skip"
    full_close = "full_close"


class PositionWorkflowInput(BaseModel):
    """
    Input to PositionWorkflow at start. Phase 0 ships the DTO slot; the workflow body lands in Phase 3.
    """

    model_config = ConfigDict(
        extra="forbid",
        json_encoders={Decimal: float},
    )
    schema_version: conint(ge=1)
    tenant_id: constr(min_length=1)
    strategy_id: constr(min_length=1)
    entry_signal_id: constr(min_length=1)
    """
    signal_id of the BTO that opened the position. Disambiguates re-BTO on the same OCC under WorkflowIDReusePolicy.REJECT_DUPLICATE.
    """
    contract_symbol: constr(min_length=1)
    """
    OCC option symbol (e.g., NVDA250516C00140000). Set as a Search Attribute 'ContractSymbol' on workflow start for STC dispatch.
    """
    qty: conint(ge=1)
    """
    Original position size, contracts.
    """
    entry_premium: Annotated[Decimal, Field(gt=0)]
    """
    Fill premium per contract, dollars (source-of-truth: broker fill, not author-posted price).
    """
    source_signal_workflow_id: str | None = None
    """
    Workflow ID of the CopytradeSignalWorkflow that spawned this position. Optional; useful for cross-workflow audit correlation.
    """
    broker_target: BrokerTarget | None = None
    """
    Phase 2c.2: broker_target carried over from the spawning CopytradeSignalWorkflow's StrategyConfig so the position's exit Activities route to the same broker task queue (broker-<value>). Optional for back-compat with pre-2c.2 replays; when absent the workflow falls back to the legacy default (broker-alpaca-paper since 2c.2). The legacy bare paper/live values are admitted ONLY for deserialization of pre-2c.2 inputs; an active position spawned with them produces a non-retryable InvalidBrokerTargetError because no worker polls broker-paper / broker-live.
    """
    eod_force_flatten: bool | None = None
    """
    Issue #202: carried over from the spawning CopytradeSignalWorkflow's StrategyConfig.eod_force_flatten. When false, PositionWorkflow does NOT arm the 15:55 ET EOD force-flatten timer (the expiry-close timer for 0DTE handling still arms unconditionally; chandelier trail, risk-breach, and operator force_close remain available as emergency exits). Optional/null treated as true to preserve pre-issue-202 behavior for replays of positions spawned before this field existed.
    """
    min_partial_qty_behavior: MinPartialQtyBehavior | None = None
    """
    Issue #205: carried over from the spawning CopytradeSignalWorkflow's StrategyConfig.min_partial_qty_behavior. Drives PositionWorkflow.processOne's pre-qtyToClose gate when remainingQty <= 1 AND floor(remainingQty * fraction) == 0. 'skip' emits PartialExitSkippedMinQty and places no order; 'full_close' closes the last contract. Optional/null treated as 'skip' to match the YAML comment's documented default. Gated behind Workflow.getVersion('min-partial-qty-skip', DEFAULT, 1) so in-flight pre-#205 workflows preserve legacy ceil(remainingQty * fraction) behavior on replay.
    """
