# generated by datamodel-codegen:
#   filename:  pre-trade-check-request.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, PositiveFloat, conint, constr


from ohmytradeagent_contract.types.broker_target import BrokerTarget


class Side(StrEnum):
    """
    BUY for BTO entries; SELL is reserved for future hardening of STC paths (currently STC bypasses the entry gate). Broker adapters only need BUY semantics in this PR.
    """

    buy = "BUY"
    sell = "SELL"


class PreTradeCheckRequest(BaseModel):
    """
    Issue #6 portfolio-level gate input. The risk-svc dispatches this to exec-svc's pre_trade_check Activity before approving entry; exec-svc forwards it to the broker port (buying_power / day-trade / margin endpoints) and returns PreTradeCheckResult. Scoped to (tenant_id, strategy_id) so multi-tenant routing in exec-svc stays uniform with placeOrder.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: conint(ge=1)
    """
    DTO contract version. See CopytradeSignalPayload.schema_version.
    """
    tenant_id: constr(min_length=1)
    strategy_id: constr(min_length=1)
    broker_target: BrokerTarget
    """
    Routes the pre-trade-check Activity to the broker-<value> task queue, mirroring OrderIntent.broker_target.
    """
    option_symbol: constr(min_length=1)
    """
    Full OCC option symbol (e.g. 'AAPL250117C00150000') the gate is evaluating, resolved upstream by ContractActivities.resolve from CopytradeSignalPayload.(ticker, expiry, strike, right). Distinct from the raw underlying ticker on the signal payload. Included so broker adapters can ask their venue for symbol-specific buying-power or margin requirements when supported.
    """
    side: Side
    """
    BUY for BTO entries; SELL is reserved for future hardening of STC paths (currently STC bypasses the entry gate). Broker adapters only need BUY semantics in this PR.
    """
    qty: conint(ge=1)
    """
    Contracts requested.
    """
    estimated_notional: PositiveFloat
    """
    Dollar notional the risk gate computed (qty * payload.price * 100 for options). Broker adapters compare this to buying_power.
    """
    correlation_id: str | None = None
    """
    Optional cross-event correlation key (typically signal_id).
    """
