# generated by datamodel-codegen:
#   filename:  premium-tick.json

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict, PositiveFloat, conint, constr


class PremiumTick(BaseModel):
    """
    Phase 4: a single premium observation for an option contract. Streamed from market-data-svc and signalled into PositionWorkflow.chandelier_tick. retrieved_at is the wire-time stamp from the source-of-truth feed.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: conint(ge=1)
    """
    DTO contract version. See CopytradeSignalPayload.schema_version.
    """
    contract_symbol: constr(min_length=1)
    """
    OCC option symbol the tick is for.
    """
    premium: PositiveFloat
    """
    Premium per contract, dollars. Source-of-truth field for the chandelier trail comparison. For chandelier-trail comparisons, market-data-svc fills this with the mid (bid+ask)/2 smoothed over a 5-10s window, not the last-trade price.
    """
    retrieved_at: AwareDatetime
    """
    RFC3339 UTC timestamp when the tick was observed by the source feed.
    """
