# generated by datamodel-codegen:
#   filename:  reconciliation-summary.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class ReconciliationSummary(BaseModel):
    """
    Return value of ReconciliationWorkflow. Counts surface in the ReconciliationCompleted audit event subject; individual discrepancies are audited as separate JournalOrphan / BrokerOrphan events at detection time.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Annotated[int, Field(ge=1)]
    journal_entries_checked: Annotated[int, Field(ge=0)]
    broker_orders_checked: Annotated[int, Field(ge=0)]
    journal_orphans: Annotated[int, Field(ge=0)]
    """
    Journal rows in non-terminal state with no matching broker order (and recorded_at older than 5 min).
    """
    broker_orphans: Annotated[int, Field(ge=0)]
    """
    Broker open orders with client_order_id not in journal.
    """
    position_orphans: Annotated[int | None, Field(ge=0)] = None
    """
    Issue #165: broker-held positions with no running PositionWorkflow. Optional + back-compat: older consumers (and older workflow versions) that don't set this field still parse cleanly.
    """
