# generated by datamodel-codegen:
#   filename:  reconciliation-workflow-input.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, conint, constr


class BrokerTarget(StrEnum):
    """
    Routes journal_dump_open + broker_list_open_orders Activities to the broker task queue.
    """

    paper = "paper"
    live = "live"


class ReconciliationWorkflowInput(BaseModel):
    """
    Input for ReconciliationWorkflow. Started by a Temporal Schedule (every 5 min + on orchestrator startup). One run per (tenant_id, strategy_id, broker_env) compares the OrderIntentJournal against the broker's open-order list and emits audit events for any discrepancies.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: conint(ge=1)
    tenant_id: constr(min_length=1)
    strategy_id: constr(min_length=1)
    broker_target: BrokerTarget
    """
    Routes journal_dump_open + broker_list_open_orders Activities to the broker task queue.
    """
