# generated by datamodel-codegen:
#   filename:  reconciliation-workflow-input.json

from __future__ import annotations


from pydantic import BaseModel, ConfigDict, conint, constr


from ohmytradeagent_contract.types.broker_target import BrokerTarget


class ReconciliationWorkflowInput(BaseModel):
    """
    Input for ReconciliationWorkflow. Started by a Temporal Schedule (every 5 min + on orchestrator startup). One run per (tenant_id, strategy_id, broker_env) compares the OrderIntentJournal against the broker's open-order list and emits audit events for any discrepancies.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: conint(ge=1)
    tenant_id: constr(min_length=1)
    strategy_id: constr(min_length=1)
    broker_target: BrokerTarget
    """
    Routes journal_dump_open + broker_list_open_orders Activities to the broker-<value> task queue. Phase 2c.2: <provider>-<env> shape (e.g. alpaca-paper). The legacy bare paper/live values are admitted ONLY for deserialization of pre-2c.2 records; using them for active reconciliation produces a non-retryable InvalidBrokerTargetError because no worker polls broker-paper / broker-live.
    """
