# generated by datamodel-codegen:
#   filename:  reset-killswitch-request.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class ResetKillSwitchRequest(BaseModel):
    """
    Update payload shared by the kill-switch reset paths (reset_killswitch / reset_account_killswitch / reset_on_activation). Single-operator reset: the workflow reset validators require ONLY approver_id_1 (non-empty; the operator, e.g. "operator:<id>"). The one-click activation reset (reset_on_activation, issued by a successful LiveActivationWorkflow.activateLive) likewise sets only approver_id_1. After reset, a configurable cool-down (cfg.reset_cooldown_secs) blocks new entries with KILL_SWITCH_COOLING_DOWN.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Annotated[int, Field(ge=1)]
    approver_id_1: Annotated[str, Field(min_length=1)]
    note: str | None = None
    """
    Operator-supplied free-form note recorded in the KillSwitchResetApproved audit event.
    """
