# generated by datamodel-codegen:
#   filename:  reset-killswitch-request.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, conint, constr


class ResetKillSwitchRequest(BaseModel):
    """
    Update payload for KillSwitchWorkflow.reset_killswitch. Dual-control required: approver_id_1 and approver_id_2 must be non-empty and distinct. Validator rejects same-approver. After reset, a configurable cool-down (cfg.reset_cooldown_secs) blocks new entries with KILL_SWITCH_COOLING_DOWN.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: conint(ge=1)
    approver_id_1: constr(min_length=1)
    approver_id_2: constr(min_length=1)
    note: str | None = None
    """
    Operator-supplied free-form note recorded in the KillSwitchResetApproved audit event.
    """
