# generated by datamodel-codegen:
#   filename:  risk-breach-payload.json

from __future__ import annotations

from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class RiskBreachPayload(BaseModel):
    """
    Signal payload fanned out by KillSwitchWorkflow.trip_killswitch to every Running workflow under TenantStrategy. PositionWorkflow.riskBreach cancels in-flight exits + flattens remaining qty; CopytradeSignalWorkflow.riskBreach audits and short-circuits the BTO/STC path.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Annotated[int, Field(ge=1)]
    reason: Annotated[str, Field(min_length=1)]
    actor: Annotated[str, Field(min_length=1)]
    occurred_at: AwareDatetime
