# generated by datamodel-codegen:
#   filename:  strategy-config.json

from __future__ import annotations

from enum import StrEnum

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    PositiveFloat,
    confloat,
    conint,
    constr,
)


class BrokerTarget(StrEnum):
    """
    Routes Activities to paper-or-live broker task queues. Phase 2a does not place orders; field reserved for Phase 2b.
    """

    paper = "paper"
    live = "live"


class StrategyConfig(BaseModel):
    """
    Per-strategy configuration loaded from tenants/<tenant>/strategies/<strategy>.yaml. Drives risk gates, sizing, and exit logic in CopytradeSignalWorkflow + PositionWorkflow. Phase 2a consumes a minimal required subset (author whitelist, signal-age, max-positions, capital-weight sizing); fields used only in later phases are optional and documented inline.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: conint(ge=1)
    """
    DTO contract version. Workers reject newer-than-build inputs to force orchestrator-svc rollback. See CopytradeSignalPayload.schema_version.
    """
    tenant_id: constr(min_length=1)
    strategy_id: constr(min_length=1)
    broker_target: BrokerTarget
    """
    Routes Activities to paper-or-live broker task queues. Phase 2a does not place orders; field reserved for Phase 2b.
    """
    author_whitelist: list[constr(min_length=1)] = Field(..., min_length=1)
    """
    Discord author IDs whose signals are admitted. Risk gate AUTHOR_NOT_WHITELISTED on miss.
    """
    max_signal_age_secs: conint(ge=1, le=3600)
    """
    Reject signals older than this. Risk gate SIGNAL_TOO_OLD on exceed.
    """
    max_positions: conint(ge=1, le=100)
    """
    Max concurrent open PositionWorkflows per (tenant, strategy). Counted via listWorkflowExecutions(TenantStrategy=..., WorkflowType='PositionWorkflow', ExecutionStatus='Running').
    """
    capital_weight: confloat(le=1.0, gt=0.0)
    """
    Fraction of strategy capital allocated per signal. allocation = capital_per_strategy * capital_weight.
    """
    min_contracts: conint(ge=1)
    """
    Lower clamp on computed quantity.
    """
    max_contracts: conint(ge=1, le=1000)
    """
    Upper clamp on computed quantity. min<=max enforced by application validator (cross-field constraint not expressible in JSON Schema).
    """
    skip_avg: bool | None = None
    """
    If true, AVG (average-down) actions are skipped by the workflow. Default true per PLAN.md Open Question #10.
    """
    default_stc_fraction: confloat(le=1.0, gt=0.0) | None = None
    """
    Phase 3: default fraction closed when an STC line has no recognized partial keyword.
    """
    partial_fractions: dict[str, confloat(le=1.0, gt=0.0)] | None = None
    """
    Phase 3: keyword -> fraction mapping for KeywordPartialMatcher (e.g. {"half": 0.5, "third": 0.33, "out": 1.0}).
    """
    pending_ttl_paper_secs: conint(ge=1) | None = None
    """
    Phase 2b/3: BTO entry order TTL for paper broker target.
    """
    pending_ttl_live_secs: conint(ge=1) | None = None
    """
    Phase 2b/3: BTO entry order TTL for live broker target.
    """
    trail_on_partial: bool | None = None
    """
    Phase 4: arm CHANDELIER_TRAIL on first partial exit.
    """
    trail_giveback_pct: confloat(le=0.5, gt=0.0) | None = None
    """
    Phase 4: trailing-stop giveback fraction once armed.
    """
    daily_loss_threshold: PositiveFloat | None = None
    """
    Phase 5: KillSwitchWorkflow auto-trip threshold (absolute dollars) on realized cumulative daily loss for (tenant, strategy). Auto-trip fires when realizedPnL <= -daily_loss_threshold. Phase 5 ships realized-only PnL composition (sum of EntryFilled/ExitFilled premia from audit_log); MTM on open positions lands in Phase 5b.
    """
    reset_cooldown_secs: conint(ge=0) | None = None
    """
    Phase 5: cool-down window (seconds) blocking new entries after a kill-switch reset. risk.check_entry rejects with KILL_SWITCH_COOLING_DOWN until cooling_down_until elapses. Closes the post-reset signal-backlog stampede vector.
    """
