# generated by datamodel-codegen:
#   filename:  strategy-config.json

from __future__ import annotations


from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    PositiveFloat,
    confloat,
    conint,
    constr,
)


from ohmytradeagent_contract.types.broker_target import BrokerTarget


class StrategyConfig(BaseModel):
    """
    Per-strategy configuration loaded from tenants/<tenant>/strategies/<strategy>.yaml. Drives risk gates, sizing, and exit logic in CopytradeSignalWorkflow + PositionWorkflow. Phase 2a consumes a minimal required subset (author whitelist, signal-age, max-positions, capital-weight sizing); fields used only in later phases are optional and documented inline.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: conint(ge=1)
    """
    DTO contract version. Workers reject newer-than-build inputs to force orchestrator-svc rollback. See CopytradeSignalPayload.schema_version.
    """
    tenant_id: constr(min_length=1)
    strategy_id: constr(min_length=1)
    broker_target: BrokerTarget
    """
    Routes Activities to the broker-<value> task queue. Phase 2c.2 introduced the <provider>-<env> shape (e.g. alpaca-paper). The legacy bare paper/live values are admitted ONLY for deserialization of pre-2c.2 audit records; configuring an active strategy with them produces a non-retryable InvalidBrokerTargetError because no worker polls broker-paper / broker-live.
    """
    author_whitelist: list[constr(min_length=1)] = Field(..., min_length=1)
    """
    Discord author IDs whose signals are admitted. Risk gate AUTHOR_NOT_WHITELISTED on miss.
    """
    max_signal_age_bto_secs: conint(ge=1, le=3600)
    """
    Reject BTO signals older than this. Risk gate SIGNAL_TOO_OLD on exceed. Issue #3 (Phase 2a hardening): the prior unified 1800s default produced systematic adverse selection on options — 0DTE / near-term premium can move 50-80% in 30 minutes during open, FOMC, or earnings windows. Defaults: 30s for BTO. Any value above 120s is an explicit per-strategy override and signals an unusual risk posture.
    """
    max_signal_age_stc_secs: conint(ge=1, le=3600)
    """
    Reject STC signals older than this. Risk gate SIGNAL_TOO_OLD on exceed. Issue #3 (Phase 2a hardening): STC tolerates a larger window than BTO because exiting late is generally safer than entering late, but a 1800s default still permits adverse selection on partial fills. Defaults: 60s for STC. Any value above 120s is an explicit per-strategy override.
    """
    bto_price_move_reject_pct: confloat(le=1.0, gt=0.0) | None = None
    """
    Issue #3 (Phase 2a hardening): BTO secondary price-move gate. Reject BTO when bid/ask (mid) has moved more than this fraction from payload.price since posted_at, regardless of signal age. Default 0.10 (10%). Documented gate spec: actual quote fetch + rejection wiring lands with market-data integration; this field is the configuration surface for the gate and the corresponding RejectionReason is BTO_PRICE_MOVED.
    """
    max_signal_age_secs: conint(ge=1, le=3600) | None = None
    """
    DEPRECATED (Issue #3): replaced by max_signal_age_bto_secs + max_signal_age_stc_secs. Retained as optional for backward-compatible deserialization of older audit/journal records only; do not set on new strategies. The per-side defaults always take precedence in RiskActivities.
    """
    max_positions: conint(ge=1, le=100)
    """
    Max concurrent open PositionWorkflows per (tenant, strategy). Counted via listWorkflowExecutions(TenantStrategy=..., WorkflowType='PositionWorkflow', ExecutionStatus='Running').
    """
    capital_weight: confloat(le=1.0, gt=0.0)
    """
    Fraction of strategy capital allocated per signal. allocation = capital_per_strategy * capital_weight.
    """
    min_contracts: conint(ge=1)
    """
    Lower clamp on computed quantity.
    """
    max_contracts: conint(ge=1, le=1000)
    """
    Upper clamp on computed quantity. min<=max enforced by application validator (cross-field constraint not expressible in JSON Schema).
    """
    skip_avg: bool | None = None
    """
    If true, AVG (average-down) actions are skipped by the workflow. Default true per PLAN.md Open Question #10.
    """
    default_stc_fraction: confloat(le=1.0, gt=0.0) | None = None
    """
    Phase 3: default fraction closed when an STC line has no recognized partial keyword.
    """
    partial_fractions: dict[str, confloat(le=1.0, gt=0.0)] | None = None
    """
    Phase 3: keyword -> fraction mapping for KeywordPartialMatcher (e.g. {"half": 0.5, "third": 0.33, "out": 1.0}).
    """
    pending_ttl_paper_secs: conint(ge=1) | None = None
    """
    Phase 2b/3: BTO entry order TTL for paper broker target.
    """
    pending_ttl_live_secs: conint(ge=1) | None = None
    """
    Phase 2b/3: BTO entry order TTL for live broker target.
    """
    max_slippage_abs: PositiveFloat | None = None
    """
    Issue #4: Absolute slippage cap (dollars per contract premium) added to payload.price when computing the BTO limit ladder. BTO limit = min(ask, payload.price + max_slippage_abs, payload.price * (1 + max_slippage_pct)). Combined with max_slippage_pct via min() so both caps apply simultaneously. Spec-only field in this PR; runtime use lands with the BTO pricing-ladder implementation.
    """
    max_slippage_pct: confloat(le=1.0, gt=0.0) | None = None
    """
    Issue #4: Fractional slippage cap (e.g. 0.05 = 5%) applied to payload.price when computing the BTO limit ladder. BTO limit = min(ask, payload.price + max_slippage_abs, payload.price * (1 + max_slippage_pct)). Combined with max_slippage_abs via min() so both caps apply simultaneously. Spec-only field in this PR; runtime use lands with the BTO pricing-ladder implementation.
    """
    repeg_after_ms: conint(ge=1) | None = None
    """
    Issue #4: Milliseconds the BTO limit sits at its initial price before a single re-peg toward the slippage-capped ceiling, after which the order is cancelled if still unfilled. Symmetric STC behavior: re-peg aggressively toward bid as the BTO-TTL window elapses. Spec-only field in this PR; runtime use lands with the BTO pricing-ladder implementation.
    """
    trail_on_partial: bool | None = None
    """
    Phase 4: arm CHANDELIER_TRAIL on first partial exit.
    """
    trail_giveback_pct: confloat(le=0.5, gt=0.0) | None = None
    """
    Phase 4: trailing-stop giveback fraction once armed. Also used as the STC giveback coefficient in the Issue #4 STC pricing ladder (limit = max(bid, ref_premium - ref_premium * trail_giveback_pct)) when no dedicated STC giveback field is configured.
    """
    daily_loss_threshold: PositiveFloat | None = None
    """
    Phase 5: KillSwitchWorkflow auto-trip threshold (absolute dollars) on realized cumulative daily loss for (tenant, strategy). Auto-trip fires when realizedPnL <= -daily_loss_threshold. Phase 5 ships realized-only PnL composition (sum of EntryFilled/ExitFilled premia from audit_log); MTM on open positions lands in Phase 5b.
    """
    reset_cooldown_secs: conint(ge=0) | None = None
    """
    Phase 5: cool-down window (seconds) blocking new entries after a kill-switch reset. risk.check_entry rejects with KILL_SWITCH_COOLING_DOWN until cooling_down_until elapses. Closes the post-reset signal-backlog stampede vector.
    """
    notional_cap_pct_of_equity: confloat(le=1.0, gt=0.0) | None = None
    """
    Issue #6 portfolio-level gate: max combined open-position notional + this signal's notional, expressed as a fraction of account equity. Reject with NOTIONAL_CAP_EXCEEDED when (sum_open_notional + new_notional) > notional_cap_pct_of_equity * equity. Opt-in: null disables the gate. Complements max_positions, which only bounds the count of concurrent positions, not their total dollar exposure.
    """
    same_underlying_count: conint(ge=1) | None = None
    """
    Issue #6 portfolio-level gate: max concurrent positions on the same underlying ticker. Reject with SAME_UNDERLYING_LIMIT when count(open positions whose underlying == payload.ticker) >= same_underlying_count. Opt-in: null disables the gate. Prevents stacking convicted-author BTOs onto a single stock during high-vol windows.
    """
    sector_concentration_cap: conint(ge=1) | None = None
    """
    Issue #6 portfolio-level gate: max concurrent positions whose underlying maps to the same sector as payload.ticker. Reject with SECTOR_CONCENTRATION_EXCEEDED when count(open positions in payload.ticker's sector) >= sector_concentration_cap. Sector mapping comes from sector_overrides; unmapped tickers are treated as sector 'unknown' and exempt from the cap. Opt-in: null disables the gate.
    """
    sector_overrides: dict[str, constr(min_length=1)] | None = None
    """
    Issue #6: ticker → sector string mapping consulted by sector_concentration_cap. Unmapped tickers resolve to 'unknown' and are exempt from the sector gate. Per-strategy overrides keep the deployable config small while letting risk-tight strategies opt in to a curated map.
    """
    daily_trade_count: conint(ge=1) | None = None
    """
    Issue #6 portfolio-level gate: max accepted BTO entries per UTC trading day. Reject with DAILY_TRADE_COUNT_EXCEEDED when today's count (from audit log: SignalAccepted with action=BTO) >= daily_trade_count. Opt-in: null disables the gate. Anti-overtrading circuit-breaker for volatile sessions.
    """
    drawdown_velocity_threshold: PositiveFloat | None = None
    """
    Issue #6 portfolio-level gate: per-minute MTM loss rate (absolute dollars/minute) at which new entries are blocked. Reject with DRAWDOWN_VELOCITY_EXCEEDED when sampled loss rate over the trailing minute >= drawdown_velocity_threshold. Opt-in: null disables the gate. Intraday rate-of-loss circuit breaker complementing daily_loss_threshold (which is a cumulative bound).
    """
    pre_trade_check_enabled: bool | None = None
    """
    Issue #6 portfolio-level gate: if true, risk.check_entry calls the exec-svc pre_trade_check Activity before approving entry. The Activity returns buying_power, pdt_status, and margin_sufficiency. Reject with PRE_TRADE_CHECK_FAILED when buying_power < new_notional, pdt_status is BLOCKED, or margin_sufficiency is false. Opt-in: null/false disables the gate.
    """
