# generated by datamodel-codegen:
#   filename:  strategy-config-update-request.json

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class StrategyConfigUpdateRequest(BaseModel):
    """
    UI-P3-b (strategy-config-write): input for the dark-gated, reduce-or-hold-risk runtime config write. The dashboard POSTs to api-gateway POST /strategy-config, which starts a short-lived StrategyConfigUpdateWorkflow on orchestrator-core, synchronously reads its StrategyConfigUpdateResult, and maps the result outcome to an HTTP status. The activity drives StrategyConfigWriter.update(tenant, strategy, config, expectedVersion, actor) — a compare-and-set gated on the reduce-or-hold-risk field-class rules. DARK by default: the api-gateway route 404s unless strategy.config.write.enabled=true. Carries NO secret/key material — config is a plain StrategyConfig blob.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Annotated[int, Field(ge=1)]
    """
    DTO contract version. See CopytradeSignalPayload.schema_version. Workers reject newer-than-build inputs.
    """
    tenant_id: Annotated[str, Field(min_length=1)]
    """
    Tenant whose strategy config is being written. The api-gateway asserts this equals the validated X-Tenant-Id before starting the workflow; StrategyConfigWriter's IDENTITY field-class check additionally hard-blocks any drift between this and config.tenant_id / the stored row.
    """
    strategy_id: Annotated[str, Field(min_length=1)]
    """
    Strategy whose config row is the compare-and-set target for (tenant_id, strategy_id). The writer's NOT_FOUND / IDENTITY gates are authoritative — a wrong/absent strategy yields NOT_FOUND, never a write.
    """
    config: dict[str, Any]
    """
    The proposed full StrategyConfig blob. Reuses the generated StrategyConfig DTO (like strategy-config.json's nested objects). StrategyConfigWriter validates it standalone, then enforces the reduce-or-hold-risk field-class rules against the currently-stored row before the CAS UPDATE.
    """
    expected_version: Annotated[int, Field(ge=0)]
    """
    Optimistic-concurrency guard: the version the caller read. The CAS UPDATE matches WHERE version = expected_version; a stale value (a concurrent writer won) yields REJECTED_STALE_VERSION.
    """
    actor: Annotated[str, Field(min_length=1)]
    """
    Who/what caused the write (e.g. the api-gateway route id). Recorded on the audit event and the strategy_config row's updated_by.
    """
    correlation_id: str | None = None
    """
    OPTIONAL cross-event correlation key (e.g. the originating request id). Embedded in the workflow id so a retried api-gateway call dedups on REJECT_DUPLICATE rather than double-writing.
    """
