# generated by datamodel-codegen:
#   filename:  subscribe-premium-request.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class SubscribePremiumRequest(BaseModel):
    """
    Phase 4: request from PositionWorkflow to market-data-svc to subscribe a premium stream for a contract. The market-data worker, on each tick, signals chandelier_tick on the named PositionWorkflow.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Annotated[int, Field(ge=1)]
    """
    DTO contract version.
    """
    tenant_id: Annotated[str, Field(min_length=1)]
    strategy_id: Annotated[str, Field(min_length=1)]
    contract_symbol: Annotated[str, Field(min_length=1)]
    """
    OCC option symbol to subscribe.
    """
    position_workflow_id: Annotated[str, Field(min_length=1)]
    """
    Target PositionWorkflow workflow_id to receive chandelier_tick signals.
    """
