# generated by datamodel-codegen:
#   filename:  subscribe-equity-request.json

from __future__ import annotations

from decimal import Decimal
from typing import Annotated

from pydantic import Field, BaseModel, ConfigDict, confloat, conint, constr


class SubscribeEquityRequest(BaseModel):
    """
    Phase 2 (watchlist-trigger): request from WatchlistTriggerWorkflow to market-data-svc to subscribe a real-time equity trade stream for a ticker. The market-data worker, on each MEANINGFUL move (min-move throttle against trigger_level x equity_emit_delta_pct), signals signal_name on the named workflow with an EquityTick payload. Mirrors SubscribePremiumRequest's tenant/strategy scoping.
    """

    model_config = ConfigDict(
        extra="forbid",
        json_encoders={Decimal: float},
    )
    schema_version: conint(ge=1)
    """
    DTO contract version.
    """
    tenant_id: constr(min_length=1)
    strategy_id: constr(min_length=1)
    ticker: constr(min_length=1)
    """
    Underlying equity symbol to subscribe (e.g. NVDA).
    """
    target_workflow_id: constr(min_length=1)
    """
    Target workflow_id to receive equity-tick signals (the WatchlistTriggerWorkflow child).
    """
    signal_name: constr(min_length=1)
    """
    Signal method name to invoke on the target workflow for each emitted tick (e.g. equityTick).
    """
    trigger_level: Annotated[Decimal, Field(gt=0)]
    """
    Reference price level T (the leg's trigger). Used as the min-move throttle base: a new tick is emitted only when |last - lastEmitted| >= equity_emit_delta_pct * T.
    """
    equity_emit_delta_pct: confloat(ge=0.0)
    """
    Minimum fractional move (of trigger_level) before a new tick is emitted. Throttles tick volume to keep workflow history bounded.
    """
