# generated by datamodel-codegen:
#   filename:  trip-killswitch-request.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, conint, constr


class TripKillSwitchRequest(BaseModel):
    """
    Update payload for KillSwitchWorkflow.trip_killswitch. Operator-issued via api-gateway POST /killswitch/trip, or auto-issued by the workflow's daily-loss heartbeat (actor=auto:daily_loss).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: conint(ge=1)
    reason: constr(min_length=1)
    """
    Free-form trip reason for audit (e.g., 'manual:operator_initiated', 'auto:daily_loss', 'auto:circuit_breaker').
    """
    actor: constr(min_length=1)
    """
    Who tripped (e.g., 'operator:ridopark', 'auto:daily_loss').
    """
    value: float | None = None
    """
    Optional numeric context for auto-trips (e.g., daily PnL when daily_loss tripped).
    """
