# generated by datamodel-codegen:
#   filename:  watchlist-trigger-payload.json

from __future__ import annotations

from decimal import Decimal
from typing import Annotated

from datetime import date
from enum import StrEnum

from pydantic import Field, BaseModel, ConfigDict, conint, constr


class Direction(StrEnum):
    """
    Price-trigger direction relative to `trigger`. ABOVE fires when the underlying trades above the level (breakout); BELOW fires when it trades below (breakdown).
    """

    above = "ABOVE"
    below = "BELOW"


class Right(StrEnum):
    """
    Option right: Call or Put. UPPERCASE.
    """

    c = "C"
    p = "P"


class Action(StrEnum):
    """
    Author intent. Watchlist triggers are entries only: buy-to-open.
    """

    bto = "BTO"


class WatchlistTriggerPayload(BaseModel):
    """
    A single armed watchlist trigger derived from a parsed daily watchlist line and emitted toward the trigger-strategy workflow. Carries the underlying ticker, the price-trigger (direction + level), and the (strike, right) option tuple to enter on breakout/retest — NOT the resolved OCC option symbol (composed downstream). Reference: docs/plans/PLAN-watchlist-trigger.html.
    """

    model_config = ConfigDict(
        extra="forbid",
        json_encoders={Decimal: float},
    )
    schema_version: conint(ge=1)
    """
    DTO contract version. See CopytradeSignalPayload.schema_version. Start at 1; bump on non-backward-compatible field changes.
    """
    tenant_id: constr(min_length=1)
    """
    Tenant scope key. Required on every Activity payload and workflow input.
    """
    strategy_id: constr(min_length=1)
    """
    Strategy scope key within the tenant.
    """
    ticker: constr(pattern=r"^[A-Z]{1,6}$")
    """
    Underlying equity ticker (e.g. 'AAPL'); uppercase, no exchange suffix. The RAW underlying — not an OCC option symbol. The full OCC symbol is composed downstream from (ticker, et_date-derived expiry, strike, right).
    """
    direction: Direction
    """
    Price-trigger direction relative to `trigger`. ABOVE fires when the underlying trades above the level (breakout); BELOW fires when it trades below (breakdown).
    """
    trigger: float
    """
    Underlying price level (dollars) that arms/fires the entry per `direction`.
    """
    strike: Annotated[Decimal, Field(gt=0)]
    """
    Option strike price (dollars).
    """
    right: Right
    """
    Option right: Call or Put. UPPERCASE.
    """
    action: Action
    """
    Author intent. Watchlist triggers are entries only: buy-to-open.
    """
    et_date: date
    """
    ET calendar date of the watchlist (YYYY-MM-DD). The America/New_York wall-clock date the trigger belongs to — NOT a timestamp. Named et_date (not date) to avoid shadowing the date type in generated models.
    """
    source_message_id: str
    """
    Discord message id the watchlist line was parsed from; the dedupe provenance.
    """
